services:
  # ---------- MOVIES SERVICE ----------
  api1:
    image: myapi:latest
    build:
      context: ./movies-service/src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-net
    depends_on:
      - redis
      - auth1
      - jaeger
    env_file:
      - ./movies-service/.env

  api2:
    image: myapi:latest
    networks:
      - app-net
    depends_on:
      - redis
      - auth2
      - jaeger
    env_file:
      - ./movies-service/.env

  theatre-db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data_movies:/var/lib/postgresql/data/
      - ./db/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    networks:
      - app-net
    env_file:
      - ./etl/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:9.1.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-net
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 10s
      timeout: 10s
      retries: 10

  init-elasticsearch:
    user: root
    image: curlimages/curl:7.85.0
    volumes:
      - ./etl/schemas/es_genres.json:/app/schemas/es_genres.json
      - ./etl/schemas/es_person.json:/app/schemas/es_person.json
      - ./etl/schemas/es_movies.json:/app/schemas/es_movies.json
      - ./etl/init-es.sh:/app/init-es.sh:ro
    networks:
      - app-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: ["sh", "-c", "tr -d '\\r' </app/init-es.sh | sh"]

  etl-filmwork:
    build:
      context: ./etl
    restart: on-failure
    networks:
      - app-net
    depends_on:
      theatre-db:
        condition: service_healthy
      init-elasticsearch:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - ./etl/.env
    environment:
      PIPELINE: filmwork

  etl-genre:
    build:
      context: ./etl
    restart: on-failure
    networks:
      - app-net
    depends_on:
      theatre-db:
        condition: service_healthy
      init-elasticsearch:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - ./etl/.env
    environment:
      PIPELINE: genre

  etl-person:
    build:
      context: ./etl
    restart: on-failure
    networks:
      - app-net
    depends_on:
      theatre-db:
        condition: service_healthy
      init-elasticsearch:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - ./etl/.env
    environment:
      PIPELINE: person

  # ---------- AUTH SERVICE ----------
  auth1:
    image: myauth:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - app-net
    depends_on:
      - redis
      - auth-db
    env_file:
      - ./auth-service/.env

  auth2:
    image: myauth:latest
    networks:
      - app-net
    depends_on:
      - redis
    env_file:
      - ./auth-service/.env

  auth-db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data_auth:/var/lib/postgresql/data/
      - ./db/database_dump_auth.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5433"
    ports:
      - "5433:5432"
    networks:
      - app-net
    env_file:
      - ./auth-service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net
    depends_on:
      - api1
      - api2
      - auth1
      - auth2

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"  # прием трассировок
      - "16686:16686"  # веб-интерфейс
    networks:
      - app-net

volumes:
  pg_data_movies:
  pg_data_auth:
  es_data:

networks:
  default:
    external: true
    name: app-net
  app-net:
    driver: bridge
