version: '3'
services:
  auth1:
    image: myauth:latest
    build:
      context: ./auth-servie
      dockerfile: Dockerfile
    depends_on: 
      - redis
    env_file:
      - ./auth-service/.env

  auth2:
    image: myauth:latest
    depends_on:
      - redis
    env_file:
      - ./auth-service/.env

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./auth-service/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth-service/configs/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth1
      - auth2

  auth-db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./auth-service/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ./auth-service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  default:
    name: app-net 